version: "6"
services:
  frontend:
    container_name: react-app
    image: react-app
    build: ./frontend/
    ports:
      - 3000:3000
  backend:
    container_name: spring-boot
    image: spring-boot
    build: ./backend/
    ports:
      - 8080:8080