name: Deployment To AWS

on:
  pull_request:
    types:
      - closed

env:
  REACT_APP_API_DOMAIN: /api
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  HOST_DNS: ${{ secrets.HOST_DNS }}
  USERNAME: ${{ secrets.USERNAME }}

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'production'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code from "production" branch
        uses: actions/checkout@v4
        with:
          ref: production # Specify the branch name to check out

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install --force
        working-directory: frontend

      - name: Build project
        run: |
          npm run build:github
          # Remove existing files in the backend's static folder
          rm -rf ../backend/src/main/resources/static/*
          # Copy new build files to the backend's static folder
          cp -r build/* ../backend/src/main/resources/static/
        working-directory: ${{ github.workspace }}/frontend

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Compiling Backend (Packaging)
        run: |
          mvn clean
          mvn package -DskipTests
        working-directory: ${{ github.workspace }}/backend

      - name: Deploy JAR to EC2
        run: |
          echo "$EC2_SSH_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem

          # Copy the JAR file to the home directory of your EC2 instance
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
          -i ssh_key.pem \
          target/backend-0.0.1-SNAPSHOT.jar \
          ${{ env.USERNAME }}@${{ env.HOST_DNS }}:~/backend-0.0.1-SNAPSHOT.jar

          # SSH into your EC2 instance
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
          -i ssh_key.pem \
          ${{ env.USERNAME }}@${{ env.HOST_DNS }} \
          "if sudo lsof -t -i :8080; then sudo kill -9 \$(sudo lsof -t -i :8080); fi" # Kill the process if it's running on port 8080

          # Start the new JAR file inside a tmux session
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
          -i ssh_key.pem \
          ${{ env.USERNAME }}@${{ env.HOST_DNS }} \
          "tmux new-session -d -s backend-session 'sudo java -jar -Dspring.profiles.active=prod backend-0.0.1-SNAPSHOT.jar'"
        working-directory: ${{ github.workspace }}/backend
